//
//  CharactersListRouter.swift
//  OpenBank
//
//  Created by Juan Carlos Perez on 1/05/20.
//  Copyright (c) 2020 Juan Carlos Perez. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol CharactersListRoutingLogic
{
  func routeToShowDetail(segue: UIStoryboardSegue?)
}

protocol CharactersListDataPassing
{
  var dataStore: CharactersListDataStore? { get }
}

class CharactersListRouter: NSObject, CharactersListRoutingLogic, CharactersListDataPassing
{
  weak var viewController: CharactersListViewController?
  var dataStore: CharactersListDataStore?
  
  // MARK: Routing
  
  func routeToShowDetail(segue: UIStoryboardSegue?)
  {
    if let segue = segue {
      let destinationVC = segue.destination as! CharacterDetailViewController
      var destinationDS = destinationVC.router!.dataStore!
      passDataToSomewhere(source: dataStore!, destination: &destinationDS)
    } else {
      let storyboard = UIStoryboard(name: "Main", bundle: nil)
      let destinationVC = storyboard.instantiateViewController(withIdentifier: "CharacterDetailViewControllerId") as! CharacterDetailViewController
      var destinationDS = destinationVC.router!.dataStore!
      passDataToSomewhere(source: dataStore!, destination: &destinationDS)
      navigateToSomewhere(source: viewController!, destination: destinationVC)
    }
  }

  // MARK: Navigation
  
  func navigateToSomewhere(source: CharactersListViewController, destination: CharacterDetailViewController)
  {
    source.show(destination, sender: nil)
  }
  
  // MARK: Passing data
  
  func passDataToSomewhere(source: CharactersListDataStore, destination: inout CharacterDetailDataStore)
  {
    destination.selectedCharacterId = source.characterId
  }
}
