//
//  CharactersListPresenter.swift
//  OpenBank
//
//  Created by Juan Carlos Perez on 1/05/20.
//  Copyright (c) 2020 Juan Carlos Perez. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CharactersListPresentationLogic
{
    func presentCharacters(response: CharactersList.Characters.Response)
    func presentLoader()
    func hideLoader()
    func presentMessage(message: String)
    func presentCharacterDetail()
}

class CharactersListPresenter: CharactersListPresentationLogic
{
  weak var viewController: CharactersListDisplayLogic?
    
    func presentCharacters(response: CharactersList.Characters.Response) {
        let viewModel = CharactersList.Characters.ViewModel(charactersList: response.charactersList)
        viewController?.displayCharacters(viewModel: viewModel)
    }
    
    func presentLoader() {
        viewController?.dysplayLoader(display: true)
    }
    
    func hideLoader() {
        viewController?.dysplayLoader(display: false)
    }
    
    func presentMessage(message: String) {
        viewController?.displayMessage(message: message)
    }
    
    func presentCharacterDetail() {
        viewController?.displayCharacterDetail()
    }
}
